/**
 * Static content for promotion, next steps, and comparisons
 * Content based on mentorship-template-pdf-content-spec.md
 */

// Pre-launch promotion checklist
export const preLaunchChecklist = [
  'Secure executive endorsement (CEO/CHRO message)',
  'Identify 3-5 program champions across departments',
  'Create teaser communications for internal channels',
  'Brief managers on program details and benefits',
  'Prepare FAQ document for common questions',
];

// During registration checklist
export const registrationChecklist = [
  'Launch multi-channel campaign (email, Slack/Teams, intranet)',
  'Host 1-2 information sessions (record for async viewing)',
  'Send manager-cascade communications',
  'Share testimonials from past participants (if available)',
  'Create urgency with deadlines (cohort) or highlight availability (evergreen)',
];

// Post-launch engagement checklist
export const postLaunchChecklist = [
  'Send welcome communications to all participants',
  'Provide first-session conversation guides',
  'Schedule automated check-in reminders',
  'Share mid-program resources and tips',
  'Celebrate milestones and participant achievements',
];

// Key messaging callout
export const keyMessagingCallout = {
  title: 'Key Messaging Tip',
  text: 'Lead with benefits, not mechanics. Every communication should answer "What\'s in it for me?" Focus on career growth, skill development, and leadership access—not program logistics.',
};

// Manual vs software comparison table
export const softwareComparison = [
  { task: 'Participant Matching', manual: '2-4 hours per 50 participants', software: '< 5 minutes' },
  { task: 'Program Setup', manual: '40+ hours', software: '4-8 hours' },
  { task: 'Progress Tracking', manual: '10+ hours/month', software: 'Automated dashboards' },
  { task: 'Session Reminders', manual: '5+ hours/month', software: 'Automated nudges' },
  { task: 'Reporting', manual: '8+ hours/month', software: 'Real-time analytics' },
];

// Benefits beyond time savings
export const softwareBenefits = [
  '95%+ match satisfaction with algorithm-based matching',
  'Built-in best practices and guided workflows',
  'Automatic engagement nudges and reminders',
  'Consistent experience across all participants',
  'Data-driven insights for continuous improvement',
  'Scalability without linear increase in admin burden',
];

// Rule of thumb callout
export const ruleOfThumbCallout = {
  title: 'When to consider software',
  text: 'At 50+ participants, manual programs become complex to manage effectively. At 100+ participants, dedicated software becomes essential for program success and administrator sanity. At 200+ participants, software will save 20+ hours per month while improving outcomes.',
};

// Next steps list
export const nextSteps = [
  'Share this template with key stakeholders (CHRO, department heads, executive sponsor)',
  'Identify your pilot group and target launch date',
  'Determine resource requirements and budget',
  'Build internal alignment and secure approvals',
  'Schedule a demo to see Together Platform in action',
];

// CTA buttons
export const ctaButtons = {
  primary: {
    text: 'Request a Demo',
    url: 'https://www.togetherplatform.com/book-a-demo',
  },
  secondary: {
    text: 'View Pricing',
    url: 'https://www.togetherplatform.com/pricing',
  },
};

// Contact information
export const contactInfo = {
  email: 'hello@togetherplatform.com',
  website: 'www.togetherplatform.com',
};

// Footer text
export const footerText = 'Generated by Together Platform Mentorship Program Builder • www.togetherplatform.com';

export default {
  preLaunchChecklist,
  registrationChecklist,
  postLaunchChecklist,
  keyMessagingCallout,
  softwareComparison,
  softwareBenefits,
  ruleOfThumbCallout,
  nextSteps,
  ctaButtons,
  contactInfo,
  footerText,
};

