import React from 'react';
import { Document, Page, View, Text } from '@react-pdf/renderer';
import { styles, BRAND_COLORS } from './styles';

// Section Components
import CoverPage from './sections/CoverPage';
import SummarySection from './sections/SummarySection';
import ProgramOutlineSection from './sections/ProgramOutlineSection';
import ROISection from './sections/ROISection';
import ResourcesSection from './sections/ResourcesSection';
import CaseStudiesSection from './sections/CaseStudiesSection';
import AboutSection from './sections/AboutSection';

const Footer = () => (
  <View style={styles.footer} fixed>
    <Text style={styles.footerText}>
      Generated by Together Platform Business Case Builder • www.togetherplatform.com
    </Text>
  </View>
);

const BusinessCasePDF = ({ selections }) => {
  return (
    <Document
      title="Business Case for Mentorship"
      author="Together Platform"
      subject="Personalized Mentorship Program Business Case"
      keywords="mentorship, ROI, business case, Together Platform"
    >
      {/* Page 1: Cover, Summary, Program Outline */}
      <Page size="A4" style={styles.page}>
        <CoverPage selections={selections} />
        <SummarySection selections={selections} />
        <ProgramOutlineSection selections={selections} />
        <Footer />
      </Page>

      {/* Page 2: ROI Analysis */}
      <Page size="A4" style={styles.page}>
        <ROISection selections={selections} />
        <Footer />
      </Page>

      {/* Page 3: Resources Comparison */}
      <Page size="A4" style={styles.page}>
        <ResourcesSection selections={selections} />
        <Footer />
      </Page>

      {/* Page 4: Case Studies */}
      <Page size="A4" style={styles.page}>
        <CaseStudiesSection selections={selections} />
        <Footer />
      </Page>

      {/* Page 5: About & Next Steps */}
      <Page size="A4" style={styles.page}>
        <AboutSection selections={selections} />
        <Footer />
      </Page>
    </Document>
  );
};

export default BusinessCasePDF;

